//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEVRE.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Data;
    using System.Data.SqlClient;
    using System.ComponentModel.DataAnnotations;
    using DEVRE.Controllers;   
    
    public class RoleModel
    {		
        [Key]
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        //public string StmtType { get; set; }
        //public string buttonText { get; set; }
        //public string Message { get; set; }
      
        //public List<Models.APIRolesModel> listUserRole { get; set; }
        ////public virtual ICollection<tbl_UserRole> tbl_UserRole { get; set; }
        //public DataTable GetAllRoles()
        //{
        //    DataTable dt = new DataTable();
        //    string strConString = @"Data Source=DEVRE;Database=Shree_Database; Integrated Security=True;";
        //    using (SqlConnection con = new SqlConnection(strConString))
        //    {
        //        con.Open();
        //        SqlCommand cmd = new SqlCommand("Select * from tbl_UserRole", con);
        //        SqlDataAdapter da = new SqlDataAdapter(cmd);
        //        da.Fill(dt);
        //    }
        //    return dt;
        //}
        //public DataTable GetRoleByID(int intRoleID)
        //{
        //    DataTable dt = new DataTable();

        //    string strConString = @"Data Source=DEVRE;Database=Shree_Database; Integrated Security=True;";

        //    using (SqlConnection con = new SqlConnection(strConString))
        //    {
        //        con.Open();
        //        SqlCommand cmd = new SqlCommand("Select * from tbl_UserRole where RoleId=" + intRoleID, con);
        //        SqlDataAdapter da = new SqlDataAdapter(cmd);
        //        da.Fill(dt);
        //    }
        //    return dt;
        //}

        //public int UpdateRole(int intRoleID, string strRoleName)
        //{
        //    string strConString = @"Data Source=DEVRE;Database=Shree_Database; Integrated Security=True;";

        //    using (SqlConnection con = new SqlConnection(strConString))
        //    {
        //        con.Open();
        //        DateTime strModifiedDate = DateTime.Now;
        //        //bool boolStatus = true;
        //        string query = "Update tbl_UserRole SET RoleName=@RoleName, strModifiedDate, boolStatus where RoleId=@RoleId";
        //        SqlCommand cmd = new SqlCommand(query, con);
        //        cmd.Parameters.AddWithValue("@RoleName", strRoleName);
        //        //cmd.Parameters.AddWithValue("@ModifiedDate", strModifiedDate);
        //        //cmd.Parameters.AddWithValue("@Status", boolStatus);
        //        cmd.Parameters.AddWithValue("@RoleId", intRoleID);
        //        return cmd.ExecuteNonQuery();
        //    }
        //}

        //public int InsertRole(string strRoleName)
        //{
        //    string strConString = @"Data Source=DEVRE;Database=Shree_Database; Integrated Security=True;";
        //    using (SqlConnection con = new SqlConnection(strConString))
        //    {
        //        con.Open();
        //        DateTime strModifiedDate = DateTime.Now;
        //        bool boolStatus = true;
        //        string query = "Insert into tbl_UserRole (RoleName, ModifiedDate,Status) values(@RoleName, strModifiedDate, boolStatus)";
        //        SqlCommand cmd = new SqlCommand(query, con);
        //        cmd.Parameters.AddWithValue("@RoleName", strRoleName);
        //  //      cmd.Parameters.AddWithValue(strModifiedDate);
        //        //cmd.Parameters.AddWithValue("@ModifiedDate", strModifiedDate);
        // //       cmd.Parameters.AddWithValue("@Status", boolStatus);                
        //        return cmd.ExecuteNonQuery();
        //    }
        //}

        //public int DeleteRole(int intRoleID)
        //{
        //    string strConString = @"Data Source=DEVRE;Database=Shree_Database; Integrated Security=True;";
        //    using (SqlConnection con = new SqlConnection(strConString))
        //    {
        //        con.Open();
        //        string query = "Delete from tbl_UserRole where RoleId=@RoleId";
                
        //        SqlCommand cmd = new SqlCommand(query, con);
        //        cmd.Parameters.AddWithValue("@RoleId", intRoleID);
        //        return cmd.ExecuteNonQuery();
        //    }
        //}
    }
}

